// Code generated by swaggo/swag. DO NOT EDIT.

package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/bha/model": {
            "get": {
                "tags": [
                    "BhaModel"
                ],
                "summary": "模型列表",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "页大小",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "模糊查询，名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "ssfs",
                                "bsd"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "模型类型",
                        "name": "types",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ListResponse-dto_BhaModelItem"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BhaModel"
                ],
                "summary": "上传模型",
                "parameters": [
                    {
                        "type": "string",
                        "description": "模型名称",
                        "name": "name",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "enum": [
                            "ssfs",
                            "bsd"
                        ],
                        "type": "string",
                        "default": "ssfs",
                        "description": "模型类型",
                        "name": "type",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "upload_file",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.CreateRes"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bha/model/{model_id}": {
            "get": {
                "description": "模型详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BhaModel"
                ],
                "summary": "模型详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "model_id",
                        "name": "model_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.BhaModelItem"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "删除模型",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "BhaModel"
                ],
                "summary": "删除模型",
                "parameters": [
                    {
                        "type": "string",
                        "description": "model_id",
                        "name": "model_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    }
                }
            }
        },
        "/bha/task/{task_id}/file/func_results": {
            "get": {
                "tags": [
                    "BhaTask"
                ],
                "summary": "func result 函数相似性对比结果",
                "parameters": [
                    {
                        "type": "string",
                        "description": "task_id",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "页大小",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "func id",
                        "name": "func_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "topN",
                        "name": "top_n",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "关键字查询",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ListResponse-models_BhaFunc"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bha/task/{task_id}/file/funcs": {
            "get": {
                "tags": [
                    "BhaTask"
                ],
                "summary": "func 检测文件函数列表",
                "parameters": [
                    {
                        "type": "string",
                        "description": "task_id",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "description": "页大小",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "关键字查询",
                        "name": "q",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.ListResponse-models_BhaFunc"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/bha/task/{task_id}/report": {
            "get": {
                "description": "获取报告",
                "produces": [
                    "application/octet-stream"
                ],
                "tags": [
                    "BhaTask"
                ],
                "summary": "获取报告",
                "parameters": [
                    {
                        "type": "string",
                        "description": "task_id",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    }
                }
            }
        },
        "/tasks": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "任务列表",
                "parameters": [
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 1,
                        "example": 1,
                        "description": "页码",
                        "name": "page",
                        "in": "query",
                        "required": true
                    },
                    {
                        "minimum": 1,
                        "type": "integer",
                        "default": 20,
                        "example": 20,
                        "description": "页大小",
                        "name": "page_size",
                        "in": "query",
                        "required": true
                    },
                    {
                        "enum": [
                            "bha"
                        ],
                        "type": "string",
                        "description": "任务模式",
                        "name": "type",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "任务id",
                        "name": "task_ids",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "名称",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "enum": [
                            "web"
                        ],
                        "type": "string",
                        "description": "来源",
                        "name": "source",
                        "in": "query"
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "queuing",
                                "processing",
                                "finished",
                                "failed",
                                "terminated"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "任务状态",
                        "name": "statuses",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "开始时间",
                        "name": "start_at",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "结束时间",
                        "name": "end_at",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/dto.ListResponse-dto_TaskListItem"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "list": {
                                                            "type": "array",
                                                            "items": {
                                                                "allOf": [
                                                                    {
                                                                        "$ref": "#/definitions/dto.TaskListItem"
                                                                    },
                                                                    {
                                                                        "type": "object",
                                                                        "properties": {
                                                                            "status": {
                                                                                "type": "string"
                                                                            }
                                                                        }
                                                                    }
                                                                ]
                                                            }
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "post": {
                "description": "#### mode为上传扫描时(默认):\n- types,必填参数\n- extra,按type分别校验\n",
                "consumes": [
                    "multipart/form-data"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "创建扫描任务",
                "parameters": [
                    {
                        "enum": [
                            0
                        ],
                        "type": "integer",
                        "description": "任务模式 0,上传扫描",
                        "name": "mode",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "任务名称",
                        "name": "name",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "description": "描述",
                        "name": "desc",
                        "in": "formData"
                    },
                    {
                        "enum": [
                            "web"
                        ],
                        "type": "string",
                        "default": "web",
                        "description": "来源",
                        "name": "source",
                        "in": "formData"
                    },
                    {
                        "type": "array",
                        "items": {
                            "enum": [
                                "bha"
                            ],
                            "type": "string"
                        },
                        "collectionFormat": "multi",
                        "description": "任务模式",
                        "name": "types",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "file",
                        "description": "文件",
                        "name": "upload_file",
                        "in": "formData"
                    },
                    {
                        "type": "string",
                        "default": "{\"bha\":{\"detection_method\": \"fast\", \"algorithm\":\"SFS\",\"model_id\": \"\"}}",
                        "description": "任务配置(默认值仅方便swagger中输入)",
                        "name": "extra",
                        "in": "formData"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "$ref": "#/definitions/dto.TaskCreateRes"
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            }
        },
        "/tasks/{task_id}": {
            "get": {
                "description": "任务详情",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "任务详情",
                "parameters": [
                    {
                        "type": "string",
                        "description": "task_id",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "allOf": [
                                {
                                    "$ref": "#/definitions/dto.Response"
                                },
                                {
                                    "type": "object",
                                    "properties": {
                                        "data": {
                                            "allOf": [
                                                {
                                                    "$ref": "#/definitions/dto.TaskDetail"
                                                },
                                                {
                                                    "type": "object",
                                                    "properties": {
                                                        "status": {
                                                            "type": "string"
                                                        }
                                                    }
                                                }
                                            ]
                                        }
                                    }
                                }
                            ]
                        }
                    }
                }
            },
            "delete": {
                "description": "删除任务，以及相应数据",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "删除任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "task_id",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    }
                }
            }
        },
        "/tasks/{task_id}/terminate": {
            "post": {
                "description": "中止任务",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "中止任务",
                "parameters": [
                    {
                        "type": "string",
                        "description": "task_id",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/dto.Response"
                        }
                    }
                }
            }
        },
        "/tasks/{task_id}/{type}/asm_file": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "任务反汇编文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "task_id",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "type",
                        "name": "type",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/tasks/{task_id}/{type}/log": {
            "get": {
                "produces": [
                    "text/plain"
                ],
                "tags": [
                    "Task"
                ],
                "summary": "任务日志文件",
                "parameters": [
                    {
                        "type": "string",
                        "description": "task_id",
                        "name": "task_id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "type",
                        "name": "type",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "skip",
                        "name": "skip",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "limit",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "dto.BhaModelItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "创建时间",
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "is_builtin": {
                    "description": "是否是内置",
                    "type": "boolean"
                },
                "md5": {
                    "type": "string"
                },
                "name": {
                    "description": "模型名称",
                    "type": "string"
                },
                "path": {
                    "description": "模型路径",
                    "type": "string"
                },
                "type": {
                    "description": "模型类型 ssfs,bsd",
                    "type": "string"
                }
            }
        },
        "dto.CreateRes": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string"
                }
            }
        },
        "dto.ListResponse-dto_BhaModelItem": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.BhaModelItem"
                    }
                }
            }
        },
        "dto.ListResponse-dto_TaskListItem": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/dto.TaskListItem"
                    }
                }
            }
        },
        "dto.ListResponse-models_BhaFunc": {
            "type": "object",
            "properties": {
                "count": {
                    "type": "integer"
                },
                "list": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.BhaFunc"
                    }
                }
            }
        },
        "dto.Response": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "err_message": {
                    "type": "string"
                }
            }
        },
        "dto.TaskCreateRes": {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "string"
                }
            }
        },
        "dto.TaskDetail": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "debug_message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "desc": {
                    "type": "string"
                },
                "detail": {
                    "type": "object",
                    "properties": {
                        "bha": {
                            "$ref": "#/definitions/models.BhaParams"
                        },
                        "sast": {
                            "$ref": "#/definitions/models.SastParams"
                        },
                        "sca": {
                            "$ref": "#/definitions/models.ScaParams"
                        }
                    }
                },
                "detect_method": {
                    "type": "string"
                },
                "err_message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "file_hash": {
                    "type": "string"
                },
                "file_path": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "modified_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "dto.TaskListItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "debug_message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "desc": {
                    "type": "string"
                },
                "detail": {
                    "type": "object",
                    "properties": {
                        "bha": {
                            "$ref": "#/definitions/models.BhaParams"
                        },
                        "sast": {
                            "$ref": "#/definitions/models.SastParams"
                        },
                        "sca": {
                            "$ref": "#/definitions/models.ScaParams"
                        }
                    }
                },
                "detect_method": {
                    "type": "string"
                },
                "err_message": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "file_hash": {
                    "type": "string"
                },
                "file_path": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "modified_at": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "source": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "task_id": {
                    "type": "string"
                },
                "types": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.BhaFunc": {
            "type": "object",
            "properties": {
                "addr": {
                    "description": "函数地址",
                    "type": "string"
                },
                "file_arch": {
                    "description": "二进制文件架构",
                    "type": "string"
                },
                "file_id": {
                    "description": "文件 id",
                    "type": "string"
                },
                "file_path": {
                    "description": "文件路径",
                    "type": "string"
                },
                "fname": {
                    "description": "检测文件函数名称",
                    "type": "string"
                },
                "id": {
                    "description": "id",
                    "type": "string"
                },
                "task_id": {
                    "description": "任务id",
                    "type": "string"
                }
            }
        },
        "models.BhaParams": {
            "type": "object",
            "properties": {
                "algorithm": {
                    "description": "检测算法 sfs,ssfs,bsd",
                    "type": "string"
                },
                "detection_method": {
                    "description": "检测方式 fast, intelligent",
                    "type": "string"
                },
                "model_id": {
                    "description": "模型id",
                    "type": "string"
                }
            }
        },
        "models.SastParams": {
            "type": "object",
            "properties": {
                "extra_params": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "lang": {
                    "type": "string"
                },
                "rule_range_ids": {
                    "description": "规则检测范围id",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "rules": {
                    "description": "自定义规则",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "models.ScaParams": {
            "type": "object",
            "properties": {
                "--optional-feature": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "reachability_analysis": {
                    "type": "boolean"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/scs/api/v1",
	Schemes:          []string{},
	Title:            "bin-vul-inspector Server API",
	Description:      "This is an bin-vul-inspector server.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
