name: Build backend image

on:
    pull_request:
      branches: [ main ]

jobs:
  package-image:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract image tag
        id: vars
        run: echo "IMAGE_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          cd backend && docker buildx build \
            --platform linux/amd64 \
            --build-arg CI_COMMIT_SHORT_SHA=${{ github.sha }} \
            --build-arg CI_COMMIT_TAG=${{ env.IMAGE_TAG }} \
            --push \
            -t ghcr.io/${{ github.repository_owner }}/bin-vul-inspector:${{ env.IMAGE_TAG }} .
